"""The rows `_capabilities.py` serves: what each command is trusted for, and the evidence."""

from __future__ import annotations

from ._capabilities_content import CONTENT_ROWS
from ._capabilities_table_2 import WRITER_ROWS
from ._capability import Capability


CAPABILITIES = (
    Capability(("project", "manifest", "diff", "decode", "neural", "recdiff"), "—",
               "yes, read-only",
               "`project`'s \"channels with inserts\" counts `.cst` labels, not loaded plugins"),
    Capability(("plugins",), "—", "yes, read-only",
               "Names every slot's plug-in — Logic's own by its slot header, with or without a float block: "
               "its 27 instruments, its nine MIDI effects (marked as such), its effects and Pedalboard's 35 "
               "stompboxes as pedals, one Logic 12.4 save of each (`instrument-*-logic`, 2026-10-05/06) — "
               "and a third-party one by the AU component "
               "identity in its embedded preset, and checks the third-party ones against `auval -a`, "
               "whose scan is kept for a day while the Components folders stay as they are (`--rescan` "
               "runs it again). A scan that leaves out a plug-in a Components folder holds is named as "
               "such, not kept, and run again when a kept one is the scan that lacks it: auval once listed only part of what was installed, while the system "
               "was still registering Audio Units (2026-10-04). "
               "A missing verdict has not yet been compared with Logic's own missing-plug-in dialog. A component whose bundle has gone bad stays in the "
               "registry, and Logic itself opened such a project without an alert (FabFilter Pro-C 2 "
               "disabled by hand, 2026-09-16); `--validate` opens each listed component with auval -v "
               "and reports it broken"),
    *CONTENT_ROWS,
    Capability(("stacks",), "CONFIRMED", "read-only until `--move`, `--move-out`, `--flatten` or `--convert`, which need `--out`",
               "Reads folder stacks and the arrange list, nested stacks included (the member byte is "
               "the depth). `--move TRACK:STACK --out DIR` writes a copy whose rows match Logic's own drag "
               "saves (2026-09-04; into and out of a nested stack 2026-09-16, the `nest-*` goldens, and "
               "Logic re-saved a nested move as written, `nest-ours-resave-logic`), through the same "
               "integrity gate as every other writer. Into a summing stack the track's output goes to "
               "the stack's bus, the row, word and UUID as Logic's own drag left them "
               "(`stack-summing-dragged-in-logic`, 2026-10-02), and Logic re-saved a written move "
               "with every row, route and stack kept (`stack-summing-move-*`). A track moved into a "
               "folder inside a summing stack keeps its output, a folder stack moved into a summing "
               "stack moves its rows alone, and a summing stack moved into one has its aux output to "
               "the outer bus, each as Logic 12.4's drag saved it (`stack-drag-into-folder-*`, "
               "`stack-folder-into-summing-*`, `stack-summing-into-summing-*`, 2026-10-04), and "
               "Logic re-saved a written copy of each as written (`-ours`, `-resave-logic`); a move "
               "that would make a third level of stack is refused. "
               "`--move-out TRACK` takes a row one level out as "
               "Logic's drags did (the `nest-*` goldens; `stack-folder-dragged-out-logic` to the top "
               "level), keeping its bus out of a summing stack (`stack-summing-dragged-out-logic`). A "
               "row that lands as a direct member of a summing stack, out of a folder or out of a "
               "summing stack inside it, outputs to that stack's bus as Logic 12.4's drags left it "
               "(`stack-out-of-folder-*`, `stack-out-of-inner-summing-*`), and Logic re-saved a written "
               "copy of each as written (2026-10-04). "
               "`--flatten STACK` writes what Logic's own Flatten Stack saved on a folder and on a "
               "summing stack (`stack-*-flattened-logic`): the header's row out, the members up a "
               "level and selected with their parents cleared, their routing and stack indices kept "
               "(inside a summing stack too, `stack-flatten-in-summing-after-logic`), "
               "the header object and its strip left in place and in use. `--convert STACK` makes a "
               "folder stack a summing stack as Logic 12.4's Track > Convert Folder Stack to Summing "
               "Stack saved it (`stack-converted-to-summing-logic`): the flatten, then a summing "
               "stack over the same members on the lowest free `Aux` and bus, the folder's header "
               "object removed, its `Sub` strip out of use, the members at stack index 0; the name "
               "stays when it was the user's, else `Sum N`, unnamed as Logic's own; the folder's Volume, "
               "Mute and Solo lanes move onto the new header as Logic's moved them "
               "(`stack-convert-lane-after-logic`, `-mutelane-`, `-sololane-`), its "
               "level and its mute stay on the `Sub` strip out of use with the aux at 0 dB and "
               "playing, as Logic left them (`stack-convert-level-after-logic`, "
               "`stack-convert-muted-after-logic`); a folder inside another folder converts as Logic's "
               "did, members and aux at stack index 0 under the outer one (`nest-convert-*-after-logic`). "
               "Members on other outputs convert as `--summing` stacks them, and members that are all "
               "their bus has take that bus's own aux as the main track, as Logic's convert does: the "
               "header carries the aux's name and its members' colour, and the track count drops by one "
               "when the aux was a track already. The removed header's row sits where Logic's convert "
               "leaves it in the mixer-order list. Logic 12.4 re-saved a written convert of each kind "
               "with every row, route, stack, index-table entry and channel record as written "
               "(`stack-convert-reuse-*`, `stack-convert-differ-*`); a folder of a tracking session "
               "converted here read as Logic's own convert of that session, every channel record "
               "included, and came back from Logic as written (2026-10-03). In that reuse the aux "
               "keeps its own level and lanes, and a folder's Volume lane moves onto it in place of its "
               "own, as Logic's did (`stack-convert-reuse-level-*`, `-lane-*`, `-both-*`, `-auxlane-*`). "
               "Refused, each named: a folder with a lane other than Volume, Mute and Solo or with an "
               "insert, a reused aux with a lane other than Volume under a folder with a Volume lane, "
               "a folder's Mute or Solo lane where its bus's aux becomes the main track, and a folder "
               "that holds a stack, which Logic's own convert turns into a track assigned to nothing "
               "(`stack-convert-holding-folder-after-logic`). "
               "A folder flattened inside another clears its members' parent as Logic's did "
               "(`nest-flatten-after-logic`). Logic 12.4 opened a "
               "written flatten of each kind and a written convert and re-saved every row, parent, "
               "route and strip as written, re-laying only the index table (`stack-*-flatten-*`, "
               "`stack-convert-*`, 2026-10-02). A summing stack whose aux is an ordinary track object "
               "is read as one: the rows under it make it a header. Two summing stacks moved into "
               "each other in turn leave their auxes feeding each other, as Logic 12.4's own two drags "
               "did with no alert (`stack-loop-*`); the write lands and names the routing loop in a "
               "warning, as any write that leaves one does"),
    Capability(("levels",), "CONFIRMED",
               "read-only until `--fader`, `--pan` or `--to`, which need `--out`",
               "Reads fader and pan, the fader in dB to the hundredth, and each channel's mute and "
               "solo, the bits Logic 12.4's own buttons set (`mute-audio-1-logic`, "
               "`solo-audio-2-logic`). `--to OTHER --out DIR` copies fader and pan onto another "
               "project through the integrity gate; a copy written onto a blank project "
               "came back from "
               "Logic's re-save with every fader and pan as written (2026-09-12). "
               "`--fader CHANNEL=DB` "
               "and `--pan CHANNEL=N` set them: a fader written at -5.3 dB and a pan at "
               "-20 read so in "
               "Logic 12.4 and came back from its save as written (`send-set-*`, "
               "2026-10-02). Logic's "
               "fader readout shows its own steps as labelled, but a level between two up to "
               "0.1 dB low (an exact -6.0 shows -6.1), so the listing gives the level as written"),
    Capability(("build", "verify", "pst", "donors", "image", "ocr"), "—",
               "never touches a project; `build`/`pst` reach Logic's own library only with "
               "`--install`",
               "A relative `output_dir` resolves under `~/Music/Audio Music Apps` — Logic's own "
               "library — and writing there is refused without `--install`. `--overwrite` is "
               "separately required to replace a file. Elsewhere: `output_root` (or `strip_root` "
               "/ `LOGICXKIT_STRIP_ROOT`, which moves `build`'s sources too), or an absolute "
               "`output_dir`"),
    Capability(("chains",), "CONFIRMED", "yes, after reading `--plan`",
               "Replaces a channel's whole chain. `--plan` names every chain it would "
               "take off; `--strict` refuses on shape drift. The real tracking chains written "
               "onto the tracking template came back from Logic's re-save with all 46 "
               "channels' chains identical (2026-09-12). A chain keyed by a channel name puts declared "
               "donors on the Stereo Out with parameters named as measured; the example mastering chain "
               "opened in Logic with every value shown as written and re-saved intact "
               "(2026-09-16, `master-ours-resave-logic`). `--verify` reads a written copy back through "
               "Logic's own Controls views (`tools/driver/controls.py`, macOS, a checkout) and names every "
               "row that differs from the file"),
    Capability(("retrack",), "CONFIRMED", "yes",
               "Changes a label, never a chain; basename-only library match. `--channel` repoints one "
               "channel at a time, so channels sharing a name can part ways: seven repointed on a "
               "tracking template showed on the Setting buttons and survived Logic's re-save "
               "byte for byte (2026-09-06)"),
    Capability(("strip-save",), "CONFIRMED", "yes",
               "A path under Logic's own library is refused without `--install` (2026-09-27)"),
    Capability(("send",), "CONFIRMED", "yes",
               "Writes to buses the caller declared missing; no cross-project bus remap. A project "
               "with no send to clone gets Logic's own from a blank project (packaged), and Logic "
               "re-saved one such add byte for byte (2026-09-13). A third send in a project whose slots "
               "start at key 2 moves the project to base 4 first, as Logic's own re-save does; left at 2 it "
               "shares slot 1's key and Logic drops the plug-in there "
               "(`legacy-migrate-fixed-*`, 2026-09-24). "
               "`--level`, `--mode` and `--bypass` write the send's level in dB, its "
               "mode and its bypass "
               "box: Logic 12.4's knobs showed -10.0 and 3.0 dB on two written sends "
               "and its save kept "
               "both records byte for byte (`send-set-*`, 2026-10-02). The level is "
               "40 * log10(position / 90), walked on Logic's knob over 265 stops; "
               "Independent Pan is "
               "read and not written. An add given none of the three comes in as Logic's own "
               "second send beside one at -16.8 dB did, at -inf, post pan and on "
               "(`send-two-base-3-logic`); a second send to a bus the channel sends to is refused. "
               "`--add` to a bus nothing uses puts it in use first, as `route` does and as Logic's own "
               "sends did (`send-bus-1-logic`); Logic 12.4 re-saved one with the send, the aux and "
               "every index-table entry as written (`send-bus-*`, 2026-10-03)"),
    Capability(("stack-create",), "CONFIRMED", "yes",
               "A session with no stack patterns on Logic's own first "
               "stack (packaged); Logic re-saved two such stacks with the header, strip and members "
               "as written (2026-09-13). The folder header's parent, colour and object id are "
               "Logic's own create's, compared record for record with its saves (`stack-sub-*-after`, "
               "`nest-inner-folder`, `stackid-*`, `gone-*`, 2026-10-04/06); Logic 12.4 re-saved two folder "
               "stacks written by that rule, at the top level and inside a summing stack, with every row, "
               "stack, strip, parent and table entry as written (`stackid-written-*`, 2026-10-06). `--summing` makes the header an aux track fed from a free "
               "bus and routes each member to it, by UUID and by index word as Logic's own Create "
               "Track Stack (Summing) wrote both; Logic 12.4 showed two written stacks, one with an "
               "instrument member, and re-saved them with every row, route and channel record as "
               "written (`stack-summing-*`, 2026-10-02). The header binds the lowest free `Aux` stub "
               "as Logic's own does, a fresh strip after the highest when none is free; Logic 12.4 "
               "re-saved two stub-bound stacks, and one inside a folder, as written "
               "(`stack-summing-stub-*`, `nest-inner-stub-*`). Direct members of one stack make a stack inside "
               "it, of either kind, as Logic's own inner Create Track Stack inside a folder wrote them "
               "(`nest-inner-*-logic`); Logic showed an outer folder holding a written summing stack "
               "and a written folder and re-saved every row, route and stack (`nest-inner-ours*`). "
               "The header outputs where every member did, or to Output 1-2 when their outputs "
               "differ, at the top level and inside a summing stack alike, as Logic 12.4's own "
               "stacks do; every channel record written is Logic's byte for byte but for the minted "
               "ids (`stack-summing-shared-*`, `stack-summing-differ-logic`, "
               "`nest-summing-in-summing-*`, 2026-10-03), and the output names each member output "
               "replaced. Members that are all their bus has get no new aux: that bus's own becomes the "
               "main track under its own name, its track moved to the header's place when it had one, "
               "with the rows, parents, colours and every channel record of Logic's own "
               "(`stack-summing-reuse-*`); `--name` is not applied there, and inside a stack it is "
               "refused as unmeasured. Logic 12.4 opened one stack by each of the three rules and "
               "re-saved it with every row, route, stack, index-table entry and channel record as "
               "written (`stack-summing-shared-*`, `-differ-*`, `-reuse-*`, 2026-10-03). "
               "A header as a member makes a stack around that stack, its rows one level in: a "
               "folder around a stack changes no routing, a summing stack around a folder routes "
               "the folder's tracks to the new bus and one around a summing stack routes that "
               "stack's aux, with the rows, parents and every channel record of Logic 12.4's own "
               "(`stack-folder-around-summing-*`, `stack-summing-around-folder-*`, "
               "`stack-summing-around-summing-after-logic`, 2026-10-04); Logic re-saved a written "
               "copy of each as written. Around a folder the new summing stack outputs to Output 1-2 "
               "and reuses no bus's aux, whatever the folder's tracks fed, on blank-born projects and "
               "on a tracking session alike (`stack-summing-busfolder-*`, `tracking-sum-busfolder-*`). "
               "A folder's header takes the lowest `Sub` strip out of use, else a new one after the "
               "highest, as Logic's own did three times (`stack-sub-*`); a strip a convert left with the "
               "folder's level or mute comes back at 0 dB and not muted, every channel record as "
               "Logic's (`stack-sub-level-*`, `stack-sub-muted-*`), and one carrying a pan, a solo, an "
               "insert or a send is refused as unmeasured. Logic re-saved a written copy "
               "of each as written. Logic's own new header takes the object id of the header the convert "
               "removed, and with it that object's mixer-order row; a written one takes a new id and the "
               "row stays. A third level of stack is refused: Logic's "
               "own Create Track Stack is disabled wherever it would make one"),
    Capability(("add-track",), "CONFIRMED", "yes",
               "Audio, instrument and aux adds; every add in one migration survived Logic's own re-save "
               "row for row (2026-09-04). A stub no track has used is never bound: a fresh channel goes "
               "there, before the Preview strip, as in eleven of Logic's own adds (`test_addtrack_strips`), "
               "and Logic's re-save kept three such byte for byte (2026-09-06). "
               "Keeps the song container's row count, the region placements and the registry's "
               "slot entries in step. `--stereo` binds the pair channel `Input N-(N+1)`, as Logic's own "
               "New Tracks did with an interface attached (2026-09-17); inside a nested stack the row "
               "takes the depth of its place, and as a direct member of a summing stack outputs to its "
               "bus, as Logic's manual has a track added to one do (in a folder inside one it keeps "
               "the main output, as Logic's drag into such a folder does). A fresh channel record goes after the highest owner below "
               "it and carries the project's slot base and shown-slot count; an instrument channel's "
               "default records are keyed to the project's slot and property bases. Logic re-saved ten "
               "chained adds with every plug-in and track (`addtrack-fresh-*`, 2026-09-23); a record out "
               "of owner order lost every plug-in (`addtrack-order-*`), and one instrument channel keyed "
               "for another base made a migration Logic would not open (`legacy-migrate-keyed-mine`). "
               "`--instrument --stereo` writes the width bytes Logic's own stereo instrument channel "
               "carries (`sessionplayer-track-logic`) and a stereo instrument slot; "
               "Logic 12.4 saved one "
               "with the channel still stereo and the slot byte for byte "
               "(`addtrack-inst-stereo-*`, "
               "2026-10-01). A Logic 11.2 project is refused, as by every writer: an "
               "instrument add "
               "written to one came back from Logic 12.4 with another instrument "
               "track left without its "
               "strip (2026-10-01)"),
    Capability(("reorder",), "CONFIRMED", "yes",
               "Moves a row among its siblings; a stack header moves with its members, and that "
               "move reproduces Logic's own drag of a header byte for byte (2026-09-12). A plain-row "
               "move came back from Logic's re-save in the written order, every row byte held but "
               "the moved row's selection mark, which Logic clears on load (2026-09-13)"),
    Capability(("route",), "CONFIRMED", "yes",
               "Sets a channel's input or output by label, by UUID and by index word; an output "
               "rerouted to a bus came back from Logic's re-save with the routing intact, and the "
               "channel record written is the one Logic saved but for the word its version sets "
               "(`route-*`, 2026-09-13). An audio track takes an input pair only when stereo and "
               "one input only when mono, as every audio track on the Logic saves measured does; "
               "`width` changes which. An output sent to a bus nothing uses puts the bus in use as "
               "Logic 12.4's own output change does (`route-out-bus-logic`): the bus takes a UUID of "
               "its own and the lowest free `Aux` comes into use fed from it, with an object, a flat "
               "row and a sequence and no track. Run on a project with outputs set to a bus still on "
               "its placeholder, the result is Logic's own save record for record, the changed "
               "channel records byte for byte but for the minted ids "
               "(`stack-summing-placeholder-before-logic` against `route-out-bus-second-logic`, "
               "2026-10-03). Logic 12.4 showed the aux beside the routed track and re-saved the copy "
               "as written (`route-bus-*`). A Logic 11.2 project is refused by its format; its "
               "class-6 channel records "
               "carry no routing uuid"),
    Capability(("arrangement",), "CONFIRMED", "yes, on a copy",
               "Reads matched Logic's display on every project tested; a rename plus a resize "
               "survived Logic's re-save byte for byte (2026-09-06), `--add` reproduces Logic's own "
               "add record for record and survived its re-save, and a move plus a delete came back "
               "from Logic's re-save event for event. On a song with no arrangement track `--add` "
               "makes the track as Logic's first section does, and Logic re-saved one with the "
               "section intact (2026-09-13). A name outside ASCII is written as UTF-8, which "
               "Logic's arrangement track showed and its re-save kept; Logic's own rename to one, "
               "an RTF record, is read (`names-text-*`, 2026-10-02)"),
    Capability(("signature",), "CONFIRMED", "yes, on a copy",
               "Reads the signature track and the LCD's division on every project tested. `--time` at "
               "bar 1, `--key` (major and minor) and `--division` reproduce Logic's own edits byte for "
               "byte (2026-09-06/07); `--key-at` and `--time-at` add changes after bar 1 and survived "
               "Logic's re-save byte for byte. `--time` at bar 1 refuses songs with later meter "
               "changes"),
    Capability(("toolbar",), "CONFIRMED", "yes, on a copy",
               "Every button's id measured on seven saves (2026-09-07) and written in Logic's order; "
               "Logic re-saved one of ours unchanged. `--row` shows or hides the toolbar row"),
    Capability(("modes",), "CONFIRMED", "yes, on a copy",
               "Cycle, Replace, Autopunch, Metronome Click, Use Musical Grid and the count-in length in "
               "the song record, pinned on Logic's saves of one press apiece (2026-09-08); a copy "
               "written with four of them came up in Logic so and was re-saved intact. Solo is read "
               "but not copied — Logic clears it on load. "
               "`apply-template` copies them"),
    Capability(("metronome",), "CONFIRMED", "yes, on a copy",
               "The Metronome and Recording panes: nine boxes, the pre-roll time, the four Klopfgeist "
               "rows and the four MIDI click rows in the click object, pinned on Logic's saves of one "
               "change apiece (2026-09-08); a copy with six boxes and the pre-roll written, and one "
               "with changed rows copied in, each came up in Logic's "
               "pane as written and re-saved intact. `apply-template` copies them"),
    *WRITER_ROWS,
)
