"""The capability rows for what a session holds — regions, markers, drums, Session Player,
automation, Library patches, MIDI and beats — spliced into `_capabilities_table` in order."""

from __future__ import annotations

from ._capability import Capability

CONTENT_ROWS = (
    Capability(("regions",), "CONFIRMED", "read yes; `--audio` and the edits on a copy",
               "Every MIDI and audio region, numbered, with its track, start, mute, loop and fades; an "
               "audio region's file record (name, format, frames, rate, channels, bits), its first frame "
               "and length in frames. Read from Logic's imports of two WAVs onto a blank-born project "
               "(2026-09-13) and Logic's own move, trim, split, mute, rename, loop, fade and import saves of "
               "one (2026-09-15, the `regions-a*` goldens): an entry pairs with its region record by slot "
               "word and piece number and with its file by slot on every project on hand with audio, so a "
               "split's second piece reads its own record. Names are UTF-8 with "
               "a byte length (region), UTF-16 LE with a unit count (file): `Snare 🥁`, `Pad — é` and "
               "`v040-日本.wav` read back as Logic wrote them. `--audio` copies a PCM WAV at the project's "
               "rate into the bundle and writes the file, region and container records held field "
               "for field to Logic's own first, second and third imports; Logic re-saved two imports "
               "written onto a blank-born project with every region record, entry and registry id as "
               "written, rewriting only each file's folder path and size, and one word of the stereo "
               "file, on load (2026-09-14). It writes onto a project with no audio regions or one whose regions "
               "are laid out as Logic's imports and splits leave them (n file records numbered 0, 4, … "
               "4(n-1) with their region records, an ordinal/link chain in file order, one registry entry "
               "each), and refuses any other layout, a WAV whose name the project already holds, and other "
               "rates and formats. The track selection is not moved. `--move`, `--trim`, `--split`, "
               "`--loop`, `--mute`, `--rename`, `--fade-in` and `--fade-out` write the fields Logic's own "
               "edits changed, and Logic re-saved a copy carrying all eight on audio and a move, both trims, "
               "a split and loops on MIDI with every region, record, entry and the split pieces' fields as "
               "written (2026-09-15, `regions-audio-edits-*` and `regions-midi-edits-*`). A split's second "
               "piece needs the file record's region count raised — Logic loads that many — and a MIDI "
               "piece plays its sequence from an offset, which the MIDI edits then refuse; an audio region's "
               "loop length is one measurement (its length in ticks times 1000). The inspector's Gain, Delay, "
               "Transpose, Fine Tune and Reverse, the Fade-Out type, the crossfade with the region over it and a "
               "region's colour read what Logic's own edits of one region wrote (2026-09-15, the `regions-b*` "
               "goldens; gain is a tens byte plus a signed five-bit remainder); `--gain`, `--delay`, `--transpose`, "
               "`--fine-tune`, `--reverse`, `--fade-out N=MS:CURVE:TYPE`, `--crossfade` and `--colour` write those fields "
               "the way Logic did, entry for entry on the save before its own, and Logic re-saved a copy carrying "
               "all of them with every field as written (`regions-params-*`), setting one more bit beside the "
               "crossfade's. Transpose on an unflexed region made Logic flex the track, which the writer does not; "
               "Logic kept the value on load, but whether it plays transposed is unheard",
               derived=("unverified",)),
    Capability(("markers",), "CONFIRMED", "yes, on a copy",
               "Reads the marker track — a marker's bar, name and length — matching Logic's Marker List on "
               "its own create, rename, move, second-marker and delete saves (2026-09-15, the `markers-a2*` "
               "goldens): 48-byte events like the arrangement's sections on the triple after the 0x11 one, "
               "names in `qSxT` records. `--add`, `--rename`, `--move` and `--delete` write those events and "
               "plain name records the way `arrangement --add` does, and Logic re-saved a copy carrying all "
               "four with both markers as written (`markers-edits-*`); Logic's own first marker also rewrote "
               "part of the registry, which ours leaves alone. A name outside ASCII is written as UTF-8, "
               "which Logic's Marker List showed and its re-save kept; Logic's own rename to one, an RTF "
               "record, is read (`names-text-*`, 2026-10-02)"),
    Capability(("quantize-drums",), "CONFIRMED", "yes, on a copy",
               "The drum-quantize procedure as file writes: groups off, the drum group with Editing "
               "(Selection) and Quantize-Locked (Audio), Q-Reference on the reference tracks, flex "
               "Slicing, and per region the two anchors plus one flex marker per hit found in the "
               "reference audio, targets on the grid, with the RBA Sequence carrying the Quantize value. "
               "Every layout is from Logic's own saves of one take (2026-09-13). Logic opened a written "
               "copy of that take reading Quantize 1/16 Note with Flex on, and its re-save kept every "
               "marker list, header, group and object field byte for byte. The hits are ours: the "
               "detector finds 78% of the transients Logic marked on that take across four grids and "
               "88% of its own are among them, so the result is a quantize, not Logic's. The "
               "reference audio is 16/24/32-bit PCM or 32/64-bit float WAV; `--grid` takes the measured "
               "4, 8, 16 or 32; a song whose tempo changes and reference audio with no hits are refused. "
               "`--bars FIRST-LAST` moves only the hits in those song bars onto the grid (each region's "
               "own Quantize value unless `--grid`) and keeps every other marker block's bytes, writing "
               "a kept Quantize-Off block as a hit block with its target unchanged; it refuses a region "
               "off the song's grid, a hit whose target would cross a kept one, and an entry naming a "
               "sequence other than an RBA Sequence, and a region already quantized keeps its one RBA "
               "Sequence. A member listing only anchors — Logic's first quantize writes the hits on the "
               "first Q-Reference region alone — takes that region's hits, and the group is reused when "
               "every member with audio regions is in it; on a take Logic itself quantized this wrote "
               "one list to every member, and Logic re-saved that `--bars 9-12` copy with every member's marker "
               "list and the drum group as written (2026-09-15, `songb-bars-9-12-*`), and those bars listen as tight as Logic's own"),
    Capability(("drums-to-midi",), "CONFIRMED", "yes, on a copy",
               "Each `--hit TRACK=TERM` audio track's hits, found by `quantize-drums`' detector, become "
               "sixteenths on the term's key in the drum map, each cut at the next note on that key, "
               "velocity from each hit's peak scaled from the track's quietest to its loudest, "
               "quantized to `--grid` when given, in one new region on a software instrument track "
               "spanning the bars that hold the quantized notes; `--threshold DB` sets the detector's "
               "floor under the track's loudest hit, `--hit TRACK=TERM:THRESHOLD` one track's own, and "
               "`--velocity FLOOR..CEILING[:GAMMA]` maps the velocities onto a band. The region is "
               "written as `midi --region` writes one and filled through the region edits, and tempo changes "
               "are refused. Logic re-saved a copy carrying the region it wrote over a real drum take with all "
               "350 notes as written (2026-09-15, `songb-drums-to-midi-*`). Listened to on that take: the kick "
               "and snare lanes are the playing. It is for drums with strong transients — kick, snare, toms; "
               "hats and cymbals ring under bleed and are not what this converts (the detector's 24 dB rise, "
               "not its floor, is what a hat never gives)"),
    Capability(("sessionplayer",), "—", "yes, read-only",
               "A Session Player region's settings from the JSON in its MneG record — Complexity "
               "(`rComp`), Fill Amount (`fillsAmount`) and Swing pinned by one editor move per save "
               "(2026-09-13) — with the drummer, preset and the generated notes' count. One region "
               "measured; records pair with drummer sequences in file order"),
    Capability(("automation",), "CONFIRMED", "read-only until `--set`, `--copy` or `--clear`, which need `--out`",
               "Reads track automation: the per-channel `*Automation` folders under the Track Automation "
               "Root Folder, their fader points (0x50: value byte, fader id) and plug-in parameter points "
               "(0x51-0x5F, 0x50 plus the mixer slot with empty slots counted, an instrument channel's "
               "instrument insert 1: a u32 over 2^31 and the parameter index; bit 14 of the type word, on "
               "some points of a real song, reads as flagged), and a region's own automation as the unreferenced "
               "sequence that names the track (2026-09-16, the `automation-*` goldens). Points were made "
               "with Create 1/2 Automation Point(s) for Visible Parameter (at the selected regions' "
               "borders) and in the Automation Event List, where Pan and the relative Volume lane were "
               "measured (the relative lane sets bit 7 of the type word's high byte). `--set`, `--copy` and "
               "`--clear` write a lane's points as the Event List does, in Logic's own order, into the track's "
               "existing folder; Logic listed three lanes written onto the blank as written and re-saved the "
               "folder byte for byte but for head +15, its selection state (`automation-ours-resave-logic`). "
               "A point's sub-tick fraction (head +2) is read and kept on a copy; Logic's own Automation Event "
               "List, read off the screen for every automation golden (2026-09-17), shows the same ticks "
               "and values as the reader, the half-tick point as the display tick before it. `--set "
               "\"TRACK:slot N NAME=V@BAR\"` writes a plug-in lane by mixer slot and parameter name in the "
               "parameter's own unit: the four natives with a map through their measured sliders (a value "
               "past a slider's end held there with a note), a third-party through its AU table (`autoset-*`); "
               "a value or bar that is not a finite number is refused. Logic's Event List named lanes at insert 4 "
               "as the Pro-Q 4 there and lanes at insert 1 as nothing (`slots-insert*`, 2026-09-23). The "
               "listing names a plug-in lane as `--set` takes it, with each point in the parameter's own "
               "unit: every index took the name Logic's Event List gave it and every point the value the "
               "Controls view showed, on the three `auto-*-resave-logic` saves"),
    Capability(("patch",), "CONFIRMED", "read yes; `--build` writes outside Logic's library unless `--install`",
               "Reads a Library patch bundle in both shapes Logic writes: its nodes, each channel's "
               "settings and the plug-ins on its strip; one Logic saved from the Library reads back "
               "with all eight inserts (2026-09-13). `--build` writes the same shape from a `.cst`; "
               "a built patch installed in the user library loaded from Logic's Library with all "
               "eight inserts on the channel. A file that does not read as a channel strip, "
               "including Logic's older-format factory strips, is refused before anything is "
               "written, and `--overwrite` replaces a bundle only once the new one is complete"),
    Capability(("midi",), "CONFIRMED",
               "read, `--export` and `--map` yes; `--region`, `--note`, the edits by region number and "
               "`--remap` on a copy",
               "Notes, controllers, program changes and pitch bends read from Logic's saves of a blank "
               "project, one field changed per save (2026-09-13); the .mid is a format-1 file at the "
               "song's PPQ with its tempo map and time signatures, one track per region, and Logic "
               "imported one and saved the same events; events before bar 1 are refused. `--region` "
               "and `--note` write what Logic's Pencil click and Event List Create wrote; a region "
               "with two notes came back from Logic's re-save note for note, and so did regions named "
               "four and nine bytes long, every word after the name as written. `--note` goes into "
               "the region on its track that holds its bar and is refused when none or several do. "
               "An un-named instrument track shows its patch's name after any load. `--transpose`, "
               "`--velocity`, `--move`, `--delete`, `--quantize`, `--copy-region`, `--copy-notes` and "
               "`--remap` rewrite a region's event lines by its listing number through the integrity gate, "
               "and Logic's re-save of one copy carrying every one of them (2026-09-14) kept every region "
               "and event as written; the number means the same region (track, start, name) in every "
               "alternative. An edit that moves an event out of its region is "
               "refused, and so is an edit, not a copy, to a sequence two regions play; a MIDI region "
               "goes only onto a software instrument track. `--map` and `--remap` use groovebin's note "
               "maps (GM percussion, Addictive Drums 2's keymap, Drum Kit Designer); the pairings between "
               "them are the tables' own, chokes and stick clicks have no GM counterpart, a region with "
               "polyphonic aftertouch is refused, and no remapped pattern has been listened to. A region name "
               "outside ASCII is written as UTF-8, as Logic's own rename wrote one. The transforms "
               "(`--select` with "
               "the operations, and the presets) rewrite the selected notes' fields through the same lines and "
               "gate, and Logic re-saved a copy carrying one of every operation and preset on 27 regions with "
               "every region and event as written (2026-09-15, `midi-transform-*`); swing's tick is the one "
               "Logic's Piano Roll wrote at 60% (`midi-qswing-60-logic`)"),
    Capability(("beats",), "CONFIRMED", "yes, on a copy",
               "The patterns, their index and the picking are groovebin's (`groovebin index`, `search`, "
               "`show`, `generate`); this writes them into a project. `place` lays one pattern, "
               "`--repeat` times, as a region from a bar whose meter must be the pattern's, `--map` "
               "translating from the map it was indexed in; `compose` writes a region per Intro, Verse, "
               "Pre-Chorus, Chorus, Bridge or Outro section from one group's patterns, with `--fills` on "
               "each section's last bar, and reports every section it skips; `generate` places a seeded "
               "phrase picked bar by bar from real library bars by their kick and snare onsets. Each "
               "region is written as `midi --region` writes one and filled through the region edits, on "
               "a software instrument track only, never lengthened for a note; the loop flag is never "
               "written and no output has been listened to. Logic re-saved a copy holding a placed pattern and a generated phrase, and one holding two composed sections with their fills, with every region and note as written (2026-09-15, `beats-place-generate-*`, `beats-compose-*`)"),
)
