"""The rows `_capabilities.py` serves: what each command is trusted for, and the evidence."""

from __future__ import annotations

from ._capabilities_content import CONTENT_ROWS
from ._capability import Capability


CAPABILITIES = (
    Capability(("project", "manifest", "diff", "decode", "neural", "recdiff"), "—",
               "yes, read-only",
               "`project`'s \"channels with inserts\" counts `.cst` labels, not loaded plugins"),
    Capability(("plugins",), "—", "yes, read-only",
               "Names every slot's plug-in — Apple's by type id, a third-party one by the AU component "
               "identity in its embedded preset — and checks the third-party ones against `auval -a`, "
               "whose scan is kept for a day while the Components folders stay as they are (`--rescan` "
               "runs it again). A scan that leaves out a plug-in a Components folder holds is named as "
               "such, not kept, and run again when a kept one is the scan that lacks it: auval once listed only part of what was installed, while the system "
               "was still registering Audio Units (2026-10-04). "
               "A missing verdict has not yet been compared with Logic's own missing-plug-in dialog. A component whose bundle has gone bad stays in the "
               "registry, and Logic itself opened such a project without an alert (FabFilter Pro-C 2 "
               "disabled by hand, 2026-09-16); `--validate` opens each listed component with auval -v "
               "and reports it broken"),
    *CONTENT_ROWS,
    Capability(("stacks",), "CONFIRMED", "read-only until `--move`, `--move-out`, `--flatten` or `--convert`, which need `--out`",
               "Reads folder stacks and the arrange list, nested stacks included (the member byte is "
               "the depth). `--move TRACK:STACK --out DIR` writes a copy whose rows match Logic's own drag "
               "saves (2026-09-04; into and out of a nested stack 2026-09-16, the `nest-*` goldens, and "
               "Logic re-saved a nested move as written, `nest-ours-resave-logic`), through the same "
               "integrity gate as every other writer. Into a summing stack the track's output goes to "
               "the stack's bus, the row, word and UUID as Logic's own drag left them "
               "(`stack-summing-dragged-in-logic`, 2026-10-02), and Logic re-saved a written move "
               "with every row, route and stack kept (`stack-summing-move-*`). A track moved into a "
               "folder inside a summing stack keeps its output, a folder stack moved into a summing "
               "stack moves its rows alone, and a summing stack moved into one has its aux output to "
               "the outer bus, each as Logic 12.4's drag saved it (`stack-drag-into-folder-*`, "
               "`stack-folder-into-summing-*`, `stack-summing-into-summing-*`, 2026-10-04), and "
               "Logic re-saved a written copy of each as written (`-ours`, `-resave-logic`); a move "
               "that would make a third level of stack is refused. "
               "`--move-out TRACK` takes a row one level out as "
               "Logic's drags did (the `nest-*` goldens; `stack-folder-dragged-out-logic` to the top "
               "level), keeping its bus out of a summing stack (`stack-summing-dragged-out-logic`). A "
               "row that lands as a direct member of a summing stack, out of a folder or out of a "
               "summing stack inside it, outputs to that stack's bus as Logic 12.4's drags left it "
               "(`stack-out-of-folder-*`, `stack-out-of-inner-summing-*`), and Logic re-saved a written "
               "copy of each as written (2026-10-04). "
               "`--flatten STACK` writes what Logic's own Flatten Stack saved on a folder and on a "
               "summing stack (`stack-*-flattened-logic`): the header's row out, the members up a "
               "level and selected with their parents cleared, their routing and stack indices kept "
               "(inside a summing stack too, `stack-flatten-in-summing-after-logic`), "
               "the header object and its strip left in place and in use. `--convert STACK` makes a "
               "folder stack a summing stack as Logic 12.4's Track > Convert Folder Stack to Summing "
               "Stack saved it (`stack-converted-to-summing-logic`): the flatten, then a summing "
               "stack over the same members on the lowest free `Aux` and bus, the folder's header "
               "object removed, its `Sub` strip out of use, the members at stack index 0; the name "
               "stays when it was the user's, else `Sum N`, unnamed as Logic's own; the folder's Volume, "
               "Mute and Solo lanes move onto the new header as Logic's moved them "
               "(`stack-convert-lane-after-logic`, `-mutelane-`, `-sololane-`), its "
               "level and its mute stay on the `Sub` strip out of use with the aux at 0 dB and "
               "playing, as Logic left them (`stack-convert-level-after-logic`, "
               "`stack-convert-muted-after-logic`); a folder inside another folder converts as Logic's "
               "did, members and aux at stack index 0 under the outer one (`nest-convert-*-after-logic`). "
               "Members on other outputs convert as `--summing` stacks them, and members that are all "
               "their bus has take that bus's own aux as the main track, as Logic's convert does: the "
               "header carries the aux's name and its members' colour, and the track count drops by one "
               "when the aux was a track already. The removed header's row sits where Logic's convert "
               "leaves it in the mixer-order list. Logic 12.4 re-saved a written convert of each kind "
               "with every row, route, stack, index-table entry and channel record as written "
               "(`stack-convert-reuse-*`, `stack-convert-differ-*`); a folder of a tracking session "
               "converted here read as Logic's own convert of that session, every channel record "
               "included, and came back from Logic as written (2026-10-03). In that reuse the aux "
               "keeps its own level and lanes, and a folder's Volume lane moves onto it in place of its "
               "own, as Logic's did (`stack-convert-reuse-level-*`, `-lane-*`, `-both-*`, `-auxlane-*`). "
               "Refused, each named: a folder with a lane other than Volume, Mute and Solo or with an "
               "insert, a reused aux with a lane other than Volume under a folder with a Volume lane, "
               "a folder's Mute or Solo lane where its bus's aux becomes the main track, and a folder "
               "that holds a stack, which Logic's own convert turns into a track assigned to nothing "
               "(`stack-convert-holding-folder-after-logic`). "
               "A folder flattened inside another clears its members' parent as Logic's did "
               "(`nest-flatten-after-logic`). Logic 12.4 opened a "
               "written flatten of each kind and a written convert and re-saved every row, parent, "
               "route and strip as written, re-laying only the index table (`stack-*-flatten-*`, "
               "`stack-convert-*`, 2026-10-02). A summing stack whose aux is an ordinary track object "
               "is read as one: the rows under it make it a header. Two summing stacks moved into "
               "each other in turn leave their auxes feeding each other, as Logic 12.4's own two drags "
               "did with no alert (`stack-loop-*`); the write lands and names the routing loop in a "
               "warning, as any write that leaves one does"),
    Capability(("levels",), "CONFIRMED",
               "read-only until `--fader`, `--pan` or `--to`, which need `--out`",
               "Reads fader and pan, the fader in dB to the hundredth, and each channel's mute and "
               "solo, the bits Logic 12.4's own buttons set (`mute-audio-1-logic`, "
               "`solo-audio-2-logic`). `--to OTHER --out DIR` copies fader and pan onto another "
               "project through the integrity gate; a copy written onto a blank project "
               "came back from "
               "Logic's re-save with every fader and pan as written (2026-09-12). "
               "`--fader CHANNEL=DB` "
               "and `--pan CHANNEL=N` set them: a fader written at -5.3 dB and a pan at "
               "-20 read so in "
               "Logic 12.4 and came back from its save as written (`send-set-*`, "
               "2026-10-02). Logic's "
               "fader readout shows its own steps as labelled, but a level between two up to "
               "0.1 dB low (an exact -6.0 shows -6.1), so the listing gives the level as written"),
    Capability(("build", "verify", "pst", "donors", "image", "ocr"), "—",
               "never touches a project; `build`/`pst` reach Logic's own library only with "
               "`--install`",
               "A relative `output_dir` resolves under `~/Music/Audio Music Apps` — Logic's own "
               "library — and writing there is refused without `--install`. `--overwrite` is "
               "separately required to replace a file. Elsewhere: `output_root` (or `strip_root` "
               "/ `LOGICXKIT_STRIP_ROOT`, which moves `build`'s sources too), or an absolute "
               "`output_dir`"),
    Capability(("chains",), "CONFIRMED", "yes, after reading `--plan`",
               "Replaces a channel's whole chain. `--plan` names every chain it would "
               "take off; `--strict` refuses on shape drift. The real tracking chains written "
               "onto the tracking template came back from Logic's re-save with all 46 "
               "channels' chains identical (2026-09-12). A chain keyed by a channel name puts declared "
               "donors on the Stereo Out with parameters named as measured; the example mastering chain "
               "opened in Logic with every value shown as written and re-saved intact "
               "(2026-09-16, `master-ours-resave-logic`)"),
    Capability(("retrack",), "CONFIRMED", "yes",
               "Changes a label, never a chain; basename-only library match. `--channel` repoints one "
               "channel at a time, so channels sharing a name can part ways: seven repointed on a "
               "tracking template showed on the Setting buttons and survived Logic's re-save "
               "byte for byte (2026-09-06)"),
    Capability(("strip-save",), "CONFIRMED", "yes",
               "A path under Logic's own library is refused without `--install` (2026-09-27)"),
    Capability(("send",), "CONFIRMED", "yes",
               "Writes to buses the caller declared missing; no cross-project bus remap. A project "
               "with no send to clone gets Logic's own from a blank project (packaged), and Logic "
               "re-saved one such add byte for byte (2026-09-13). A third send in a project whose slots "
               "start at key 2 moves the project to base 4 first, as Logic's own re-save does; left at 2 it "
               "shares slot 1's key and Logic drops the plug-in there "
               "(`legacy-migrate-fixed-*`, 2026-09-24). "
               "`--level`, `--mode` and `--bypass` write the send's level in dB, its "
               "mode and its bypass "
               "box: Logic 12.4's knobs showed -10.0 and 3.0 dB on two written sends "
               "and its save kept "
               "both records byte for byte (`send-set-*`, 2026-10-02). The level is "
               "40 * log10(position / 90), walked on Logic's knob over 265 stops; "
               "Independent Pan is "
               "read and not written. An add given none of the three comes in as Logic's own "
               "second send beside one at -16.8 dB did, at -inf, post pan and on "
               "(`send-two-base-3-logic`); a second send to a bus the channel sends to is refused. "
               "`--add` to a bus nothing uses puts it in use first, as `route` does and as Logic's own "
               "sends did (`send-bus-1-logic`); Logic 12.4 re-saved one with the send, the aux and "
               "every index-table entry as written (`send-bus-*`, 2026-10-03)"),
    Capability(("stack-create",), "CONFIRMED", "yes",
               "A session with no stack patterns on Logic's own first "
               "stack (packaged); Logic re-saved two such stacks with the header, strip and members "
               "as written (2026-09-13). `--summing` makes the header an aux track fed from a free "
               "bus and routes each member to it, by UUID and by index word as Logic's own Create "
               "Track Stack (Summing) wrote both; Logic 12.4 showed two written stacks, one with an "
               "instrument member, and re-saved them with every row, route and channel record as "
               "written (`stack-summing-*`, 2026-10-02). The header binds the lowest free `Aux` stub "
               "as Logic's own does, a fresh strip after the highest when none is free; Logic 12.4 "
               "re-saved two stub-bound stacks, and one inside a folder, as written "
               "(`stack-summing-stub-*`, `nest-inner-stub-*`). Direct members of one stack make a stack inside "
               "it, of either kind, as Logic's own inner Create Track Stack inside a folder wrote them "
               "(`nest-inner-*-logic`); Logic showed an outer folder holding a written summing stack "
               "and a written folder and re-saved every row, route and stack (`nest-inner-ours*`). "
               "The header outputs where every member did, or to Output 1-2 when their outputs "
               "differ, at the top level and inside a summing stack alike, as Logic 12.4's own "
               "stacks do; every channel record written is Logic's byte for byte but for the minted "
               "ids (`stack-summing-shared-*`, `stack-summing-differ-logic`, "
               "`nest-summing-in-summing-*`, 2026-10-03), and the output names each member output "
               "replaced. Members that are all their bus has get no new aux: that bus's own becomes the "
               "main track under its own name, its track moved to the header's place when it had one, "
               "with the rows, parents, colours and every channel record of Logic's own "
               "(`stack-summing-reuse-*`); `--name` is not applied there, and inside a stack it is "
               "refused as unmeasured. Logic 12.4 opened one stack by each of the three rules and "
               "re-saved it with every row, route, stack, index-table entry and channel record as "
               "written (`stack-summing-shared-*`, `-differ-*`, `-reuse-*`, 2026-10-03). "
               "A header as a member makes a stack around that stack, its rows one level in: a "
               "folder around a stack changes no routing, a summing stack around a folder routes "
               "the folder's tracks to the new bus and one around a summing stack routes that "
               "stack's aux, with the rows, parents and every channel record of Logic 12.4's own "
               "(`stack-folder-around-summing-*`, `stack-summing-around-folder-*`, "
               "`stack-summing-around-summing-after-logic`, 2026-10-04); Logic re-saved a written "
               "copy of each as written. Around a folder the new summing stack outputs to Output 1-2 "
               "and reuses no bus's aux, whatever the folder's tracks fed, on blank-born projects and "
               "on a tracking session alike (`stack-summing-busfolder-*`, `tracking-sum-busfolder-*`). "
               "A folder's header takes the lowest `Sub` strip out of use, else a new one after the "
               "highest, as Logic's own did three times (`stack-sub-*`); a strip a convert left with the "
               "folder's level or mute comes back at 0 dB and not muted, every channel record as "
               "Logic's (`stack-sub-level-*`, `stack-sub-muted-*`), and one carrying a pan, a solo, an "
               "insert or a send is refused as unmeasured. Logic re-saved a written copy "
               "of each as written. Logic's own new header takes the object id of the header the convert "
               "removed, and with it that object's mixer-order row; a written one takes a new id and the "
               "row stays. A third level of stack is refused: Logic's "
               "own Create Track Stack is disabled wherever it would make one"),
    Capability(("add-track",), "CONFIRMED", "yes",
               "Audio, instrument and aux adds; every add in one migration survived Logic's own re-save "
               "row for row (2026-09-04). With no audio stub free a fresh channel is made where "
               "Logic makes one, and Logic's re-save kept three such byte for byte (2026-09-06). "
               "Keeps the song container's row count, the region placements and the registry's "
               "slot entries in step. `--stereo` binds the pair channel `Input N-(N+1)`, as Logic's own "
               "New Tracks did with an interface attached (2026-09-17); inside a nested stack the row "
               "takes the depth of its place, and as a direct member of a summing stack outputs to its "
               "bus, as Logic's manual has a track added to one do (in a folder inside one it keeps "
               "the main output, as Logic's drag into such a folder does). A fresh channel record goes after the highest owner below "
               "it and carries the project's slot base and shown-slot count; an instrument channel's "
               "default records are keyed to the project's slot and property bases. Logic re-saved ten "
               "chained adds with every plug-in and track (`addtrack-fresh-*`, 2026-09-23); a record out "
               "of owner order lost every plug-in (`addtrack-order-*`), and one instrument channel keyed "
               "for another base made a migration Logic would not open (`legacy-migrate-keyed-mine`). "
               "`--instrument --stereo` writes the width bytes Logic's own stereo instrument channel "
               "carries (`sessionplayer-track-logic`) and a stereo instrument slot; "
               "Logic 12.4 saved one "
               "with the channel still stereo and the slot byte for byte "
               "(`addtrack-inst-stereo-*`, "
               "2026-10-01). A Logic 11.2 project is refused, as by every writer: an "
               "instrument add "
               "written to one came back from Logic 12.4 with another instrument "
               "track left without its "
               "strip (2026-10-01)"),
    Capability(("reorder",), "CONFIRMED", "yes",
               "Moves a row among its siblings; a stack header moves with its members, and that "
               "move reproduces Logic's own drag of a header byte for byte (2026-09-12). A plain-row "
               "move came back from Logic's re-save in the written order, every row byte held but "
               "the moved row's selection mark, which Logic clears on load (2026-09-13)"),
    Capability(("route",), "CONFIRMED", "yes",
               "Sets a channel's input or output by label, by UUID and by index word; an output "
               "rerouted to a bus came back from Logic's re-save with the routing intact, and the "
               "channel record written is the one Logic saved but for the word its version sets "
               "(`route-*`, 2026-09-13). An audio track takes an input pair only when stereo and "
               "one input only when mono, as every audio track on the Logic saves measured does; "
               "`width` changes which. An output sent to a bus nothing uses puts the bus in use as "
               "Logic 12.4's own output change does (`route-out-bus-logic`): the bus takes a UUID of "
               "its own and the lowest free `Aux` comes into use fed from it, with an object, a flat "
               "row and a sequence and no track. Run on a project with outputs set to a bus still on "
               "its placeholder, the result is Logic's own save record for record, the changed "
               "channel records byte for byte but for the minted ids "
               "(`stack-summing-placeholder-before-logic` against `route-out-bus-second-logic`, "
               "2026-10-03). Logic 12.4 showed the aux beside the routed track and re-saved the copy "
               "as written (`route-bus-*`). A Logic 11.2 project is refused by its format; its "
               "class-6 channel records "
               "carry no routing uuid"),
    Capability(("arrangement",), "CONFIRMED", "yes, on a copy",
               "Reads matched Logic's display on every project tested; a rename plus a resize "
               "survived Logic's re-save byte for byte (2026-09-06), `--add` reproduces Logic's own "
               "add record for record and survived its re-save, and a move plus a delete came back "
               "from Logic's re-save event for event. On a song with no arrangement track `--add` "
               "makes the track as Logic's first section does, and Logic re-saved one with the "
               "section intact (2026-09-13). A name outside ASCII is written as UTF-8, which "
               "Logic's arrangement track showed and its re-save kept; Logic's own rename to one, "
               "an RTF record, is read (`names-text-*`, 2026-10-02)"),
    Capability(("signature",), "CONFIRMED", "yes, on a copy",
               "Reads the signature track and the LCD's division on every project tested. `--time` at "
               "bar 1, `--key` (major and minor) and `--division` reproduce Logic's own edits byte for "
               "byte (2026-09-06/07); `--key-at` and `--time-at` add changes after bar 1 and survived "
               "Logic's re-save byte for byte. `--time` at bar 1 refuses songs with later meter "
               "changes"),
    Capability(("toolbar",), "CONFIRMED", "yes, on a copy",
               "Every button's id measured on seven saves (2026-09-07) and written in Logic's order; "
               "Logic re-saved one of ours unchanged. `--row` shows or hides the toolbar row"),
    Capability(("modes",), "CONFIRMED", "yes, on a copy",
               "Cycle, Replace, Autopunch, Metronome Click, Use Musical Grid and the count-in length in "
               "the song record, pinned on Logic's saves of one press apiece (2026-09-08); a copy "
               "written with four of them came up in Logic so and was re-saved intact. Solo is read "
               "but not copied — Logic clears it on load. "
               "`apply-template` copies them"),
    Capability(("metronome",), "CONFIRMED", "yes, on a copy",
               "The Metronome and Recording panes: nine boxes, the pre-roll time, the four Klopfgeist "
               "rows and the four MIDI click rows in the click object, pinned on Logic's saves of one "
               "change apiece (2026-09-08); a copy with six boxes and the pre-roll written, and one "
               "with changed rows copied in, each came up in Logic's "
               "pane as written and re-saved intact. `apply-template` copies them"),
    Capability(("width",), "CONFIRMED", "yes, on a copy",
               "A channel's width and the build of every plug-in on it, measured across real sessions "
               "and a Logic-written stereo bus; two auxes made stereo on two templates came back "
               "stereo from Logic's re-save, slots included (2026-09-08)"),
    Capability(("tempo",), "CONFIRMED", "yes, on a copy",
               "Reads matched every project's LCD, ramps and steps included; `--set 180` showed 180 on "
               "Logic's LCD and survived its re-save (2026-09-06); "
               "`--add` writes the bare step Logic's Tempo List makes and survived its re-save; "
               "`--ramp` writes the event run Logic's Tempo Operations curve makes and survived "
               "its re-save event for event. Hand-drawn curves (the 0xb4 line) are read only"),
    Capability(("rename", "colour", "hide"), "CONFIRMED", "yes",
               "Applied across three legacy migrations Logic re-saved unchanged (2026-09-04); a "
               "rename marks the name as the user's, else the arrange shows the strip "
               "setting's name; "
               "a name outside ASCII is written as UTF-8 with its byte length, the "
               "object Logic's own "
               "rename wrote (`names-non-ascii-logic`), and Logic 12.4 saved a copy "
               "carrying three with "
               "each as written (`names-write-*`, 2026-10-01) and one with names of 64, 96 and 127 "
               "bytes (`names-long-*`)"),
    Capability(("settings",), "CONFIRMED", "yes; `--set` writes a copy",
               "A slot's settings in its family's vocabulary through the plug-in's map "
               "(`data/translate`): a third-party's from its AU state's id/value pairs (Pro-C 2, "
               "with the normalized ratio, attack and release read off curves the AU host sampled) or "
               "its vendor blob (sonible's smart:comp 2 and smart:gate, real units in their protobuf "
               "block, `sonible-*`), its FabFilter binary state by band (Pro-Q 4) or its zlib JSON state "
               "(iZotope's Neutron 5, real units by module: a compressor, a gate and an EQ at once, a line "
               "per family, `neutron-*`), one of Logic's own from its measured table (Compressor, Noise Gate, "
               "Channel EQ, Multipressor), a multiband's as bands by frequency range (Pro-MB, Multipressor). "
               "A slot without a map says so. `--set` writes the same names into one slot: one of Logic's "
               "own through its table, each value held to its measured slider's ends and put on the nearer sampled "
               "position — the knob rows are sampled at every unit, the dB rows every few, where a value between "
               "samples is written as given with a note (`snap-*`), "
               "FabFilter's pairs or binary state patched in place inside the record's plist at the same "
               "length (sonible's protobuf and iZotope's JSON are read, not written); an EQ takes "
               "`band N=<shape> <freq> …`, rewriting that band and no other. `--at` is the mixer slot. "
               "Three items written into a Pro-C 2 came back from Logic's re-save shown as written, the "
               "other nine and the side chain untouched (`write-proc-*`, 2026-09-23)"),
    Capability(("transplant",), "CONFIRMED", "yes, within the channel's key range",
               "Each slot's side chain follows its source's name into the destination (payload "
               "+144/+145, the `sidechain-*` goldens) or is cleared with a report line. "
               "Refuses a move that overruns the slot key range — which deletes the channel's "
               "`.cst` reference record, a loss `validate_project` cannot see — and one that "
               "crosses a record class version; `--force` writes anyway. Clones take the "
               "destination's own slot keys (2 in projects whose slots start there). Two native "
               "slots moved between blank-born projects came back from Logic's re-save byte for "
               "byte (2026-09-13). One source fanned out to several channels gives each copy its "
               "own instance id, measured from a second instance of that plug-in in the source; "
               "without one the fan-out is refused. So is a third-party slot onto an audio channel of the "
               "other width (Logic's own are re-stamped; an instrument channel's width byte says "
               "nothing about its plug-in). `--stack NAME=SRC` targets a folder stack's "
               "members. One Auto-Align 2 fanned out onto a tracking song's seventeen drum channels "
               "came back from Logic's re-save with every slot byte for byte, the seventeen "
               "stamped ids included (2026-09-21, `transplant-fanout-*`). The destination's plug-in "
               "automation lanes are left as they are"),
    Capability(("bypass",), "CONFIRMED", "yes",
               "Flips the bypass bit on the slots a channel already carries; adds nothing and "
               "removes nothing. Two bypassed slots came back from Logic's re-save with the bits "
               "as written (2026-09-13)"),
    Capability(("add-plugin",), "CONFIRMED", "yes, on a copy",
               "A library plug-in into mixer slot N (from 1, empty slots counted — the insert automation "
               "names), the end without: an empty slot takes it where it is, an occupied one moves it "
               "and every later slot down a key with their automation lanes (`slots-front-*`: Logic's "
               "Event List named every lane's plug-in, 2026-09-23). An instrument channel's slot 1 is its "
               "instrument; an effect is refused there and an append lands at 2 (`slots-inst-*`). "
               "`--set` on one of Logic's own holds a value to its slider's measured ends with a note and "
               "puts it on the slider's grid. The donor is stamped as `transplant` "
               "stamps one (owner, key, index, width for Logic's own, id, bypass, the side chain "
               "`--side-chain NAME` asks for by name, none otherwise — Logic showed a written one "
               "in the plug-in header and re-saved it as written, `sidechain-ours-resave-logic`), "
               "the slots from "
               "that position on move down a key, header key and +6 index both, and the "
               "channel's Smart Control mappings move with them (without that Logic reset the "
               "channel). A chain reaching the two keys under the reference record moves the "
               "reference, the records under it and the archives above it up on every channel, "
               "and every channel record's shown-slot count follows. Logic's own appends on the "
               "`master-track-*` saves are reproduced slot for slot and the channel record byte "
               "for byte; Logic re-saved a mid-chain insert and an append with every slot, "
               "archive and channel record as written but a per-plug-in token on the new slot "
               "(2026-09-21, `addplugin-mid-*`, `addplugin-end-*`), and Auto-Align 2 into slot 1 "
               "of a tracked song's seventeen drum channels in front of their chains, the range "
               "grown by the project's own headroom (`addplugin-front-*`). Third-party plug-ins "
               "come from `logic donors PROJECT [--as NAME] [--refresh]`, one donor per width. A side "
               "chain may also be an input of the interface or an instrument track "
               "(`sidechain-input2-logic`, `sidechain-inst-*`)"),
    Capability(("tracking-chains",), "CONFIRMED", "yes, on a copy",
               "Every third-party slot with a translation map replaced by Logic's own of its family with the "
               "settings carried (the `replace-plugin --translate` path; Neutron 5 one native per live element, "
               "the extras added after the first), a third-party without a map removed, the natives that carry "
               "lookahead bypassed, one it made from a third-party too (a Pro-MB's Multipressor, `mb-promb`). "
               "Logic-confirmed 2026-09-24 (`trk-*`): a Neutron 5 read back as the Channel "
               "EQ and Compressor it became, both Controls views on the carried values, and a re-save kept every "
               "swap and every bypass on two channels and the output. An instrument channel keeps its "
               "instrument, whatever it is (2026-09-27)"),
    Capability(("swap-plugin",), "CONFIRMED", "yes, on a copy",
               "Every slot holding one plug-in replaced by another across the project, each through the "
               "`replace-plugin --translate` path: settings through the family vocabulary, side chains and "
               "automation lanes carried, a slot whose settings cannot cross left as it is with the reason; a "
               "`--from` no slot holds, or one naming the `--to` plug-in, refused before a copy is made. "
               "The replacement and the carry are the Logic-confirmed ones (`slots-replace4-*`, `translate-*`, "
               "`auto-lanes-*`); the loop itself Logic-confirmed on two smart:comp 2 slots into Compressors, "
               "both channels' Controls views reading the carried values (`swap-*`, 2026-09-24), and again "
               "with the packaged donors only (`swap-packaged-*`, 2026-09-25): the same carried values, and "
               "Auto Release reading 1 — the packaged `#default` donor's — where the data root's `Drum Mix` "
               "donor had read 0. The 2026-09-24 copies, and the `translate-*` ones, took a Compressor donor "
               "harvested from a real project — the packaged donor's layout and length, its preset name, "
               "values and instance id aside"),
    Capability(("remove-plugin", "replace-plugin"), "CONFIRMED", "yes, on a copy",
               "The plug-in in mixer slot N out of a channel, the slots after it moved up a key with their "
               "automation lanes and Smart Control mappings, the removed slot's dropped (`slots-remove-*`, "
               "Logic's Event List named the rest on their own plug-ins, 2026-09-23); an instrument "
               "channel's instrument leaves its slot empty. "
               "`replace-plugin` is that removal and an `add-plugin` at the same slot. Logic "
               "re-saved both with every slot as written, the replace's archives and channel "
               "record too (2026-09-22, `addplugin-remove-*`, `addplugin-replace-*`); the key "
               "range is left for Logic to re-lay out on save. "
               "`replace-plugin --translate` carries the old slot's settings through the family "
               "vocabulary: a Pro-C 2 dialled in Logic to -30 dB / 3.06:1 / 10.72 ms / 115 ms / 6 dB "
               "knee / +3 dB / 80 % went into a Compressor that Logic showed as -30 dB, 3.1:1, 10.5 ms, "
               "110 ms, +3 dB, knee 0.1, 80 % and kept so on re-save (`translate-*`, 2026-09-22) — its "
               "own grids, which the map rounds to; attack and release sit on their knobs' positions and "
               "are written as read (a smart:comp 2 into a Compressor and a smart:gate into a Noise Gate "
               "came back the same way, `translate-sonible-resave-logic`). "
               "Knee is approximate (dB/72); Pro-C 2's look-ahead, auto gain, range, hold and style have no "
               "analogue and are reported, not guessed, as is the Compressor's circuit the other way; the "
               "target keeps its own. An EQ crosses as bands: a Pro-Q 4 dialled "
               "to nine bands went into a Channel EQ that Logic showed with the low cut, four bells, "
               "high shelf and high cut as planned and re-saved as written but for its knobs' own "
               "frequency and Q positions (250.01 Hz to 250, Q 2.43 to 2.50; `translate-proq-*`, "
               "2026-09-22); the notch and the fifth bell were reported, not placed. The slot's automation "
               "lanes follow the translation (`automation_remap`): a Pro-C 2's threshold, ratio and attack lanes "
               "landed on the Compressor's indices in its slider units and Logic's Event List listed them by "
               "name, its Controls view following them in Read — -30, -24, -12 dB, 3.9:1 and 2.7:1, 16 ms "
               "(`auto-lanes-*`, 2026-09-23); a lookahead lane with no analogue was dropped with a line. "
               "An EQ's or a multiband's lanes cross by band, onto the band the plan placed each in: a "
               "Pro-Q 4's low-cut on/off, bell gain and bell frequency lanes reached the Channel EQ's Low "
               "Cut, Peak 1 and Peak 3 and read 1/0/1, -4/0/+6 dB and 1000/2000 Hz, a Pro-MB's threshold, "
               "ratio and level lanes the Multipressor's band 1 and 4 and read -20/-12/-30 dB, 3.675 and "
               "1.977 (its ratio knob's grid), +1 dB (`auto-eqlanes-*`, `auto-mblanes-*`, 2026-09-23); "
               "the four natives' sliders are measured for it. `--keep-automation` leaves the lanes; with "
               "neither they are dropped with a line, and so is the side chain. The other way "
               "round, a FabFilter replacement takes the plan into its own state: Logic's Compressor "
               "into a Pro-C 2 that Logic showed as -30 dB, 3.10:1, 10.49 ms, 109.8 ms, +7.20 dB knee, "
               "+3 dB, 80 % (attack and release land between the sampled curve's points; "
               "`write-comp2proc-*`), and a Channel EQ into a Pro-Q 4 whose seven bands Logic showed as "
               "written, the off low shelf left out (`write-eq2proq-*`, 2026-09-23); what the donor keeps "
               "of its own is reported. A multiband compressor crosses as bands by frequency range: a "
               "Pro-MB's three bands went into a Multipressor Logic showed as written but for its ratio "
               "and crossover knobs (4.0 as 3.675, 4 kHz as 3.9), and that re-save came back into a "
               "Pro-MB as written (`mb-*`, 2026-09-23). A stretch no source band covers is a live band "
               "at ratio 1, since an off band's range goes to the next live one (`mb-neutral-*`); Pro-MB's "
               "range limit and percentage times are reported, not guessed. A Multipressor band crosses "
               "into a Pro-MB band as one side, its expander when the compressor is neutral, else its "
               "compressor, the plan naming the side; that side's lanes carry (the expander's threshold, "
               "ratio and reduction onto an expand band's threshold, ratio and range) and the other "
               "side's stay behind with the reason"),
    Capability(("clear-slots",), "CONFIRMED", "yes",
               "Drops the records and their key flags; the `.cst` reference label stays. Opened in "
               "Logic with the inserts empty (2026-09-04); without the flag sync Logic refuses the file"),
    Capability(("header",), "CONFIRMED", "yes",
               "Every bit measured on seventeen single-toggle saves; a written set opened in Logic "
               "showing all sixteen components as set"),
    Capability(("prefs",), "CONFIRMED", "yes, with Logic closed",
               "Logic's own settings: 150 controls across every Settings pane pinned by single "
               "changes (General > Editing 2026-09-05, the rest 2026-09-08); a box written with Logic "
               "closed came up that way on relaunch. Not carried: Audio > Devices, Plug-in Delay "
               "Compensation, Control Surfaces (Logic's own file). Writes go through `defaults`, are "
               "refused while Logic runs, and take a backup first"),
    Capability(("controlbar",), "CONFIRMED", "yes",
               "Every id measured on fifty single-toggle saves (2026-09-04); a bar copied whole "
               "onto another project came up in Logic with that set. Both display-state files written"),
    Capability(("group",), "CONFIRMED", "yes",
               "Every box and the member events measured on twenty-eight single-change saves "
               "(2026-09-05); the writer reproduces six of Logic's saves byte for byte, and a "
               "migrated song with two groups opened in Logic showing them and re-saved with the "
               "identical group records and row list. Leaving a group: Logic's own No Group on a member (2026-09-12) matches the composed leave outside the selection bytes. "
               "A name outside ASCII is UTF-8 by its byte length, as Logic's own rename wrote one; "
               "Logic's Groups inspector showed one written here (`names-text-*`, 2026-10-02)"),
    Capability(("apply-template",), "CONFIRMED", "yes, with a map across lineages",
               "Same lineage pairs by object id; across lineages `--map FILE` says how tracks pair "
               "(`--propose-map` drafts it, `(none)` leaves a track alone). Legacy songs "
               "migrated onto a mixing template opened in Logic and re-saved with the identical "
               "row list (2026-09-04). Never removes a send; inputs past the session's count are made "
               "before planning (Logic re-saved six); the template's groups are made and joined by "
               "name (2026-09-05, confirmed on the same song). Legacy bus returns the template "
               "duplicates are silenced; `-` lines in the map leave template tracks out. A song "
               "whose slots start at key 2 beside three sends is moved to base 4 in the same pass, as Logic's own re-save does; a project born at base 2 without that collision is left there "
               "(`logic/README.md`: slot keys). Also carries the track power state, icons, "
               "header components and the control bar; not the project's own tempo, meter or key, "
               "which stay the song's. The current tracking template applied onto a tracked song "
               "(2026-09-16) re-saved in Logic with the identical row list and strip references, "
               "two of them repointed per channel. "
               "A template stack is the session stack its header pairs with, else the one stack "
               "of its name; two of the name with neither paired refuse the move; a stack of tracks "
               "the plan adds is made once they exist. An output to a "
               "bus the template returns and the session will not is refused. "
               "A Logic 11.2 save serves as the template: its routing is read from the channel "
               "records' index words (every routed channel as Logic 12.4 converted it, "
               "2026-10-02); its chains are refused, its slot records being another class"),
    Capability(("migrate",), "CONFIRMED", "yes, on a renamed copy; across lineages only with `--map` or `--force`",
               "Composes `propose-map` (or `--map FILE`) with `apply-template`'s step into "
               "`CLAUDE migrated - <song>.logicx`: the ops are apply-template's CONFIRMED writers, "
               "A session of the template's lineage "
               "pairs by object id and the draft is not applied. `--verify` drives Logic Pro — opens "
               "the copy, Save As through `tools/driver`, closes without saving — and compares the "
               "row lists ignoring only the flag word; it runs from a checkout on macOS with Logic "
               "installed and has not yet been run against Logic. Logic re-saved a migrated legacy session "
               "with every row and plug-in as written (2026-09-24, `legacy-migrate-fixed-*`)"),
)
